enableColors: true

enableHyperlinks: true

enableMessageNames: true

enableProgressBars: true

nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

preferInteractive: true

progressBarStyle: patrick

yarnPath: .yarn/releases/yarn-3.2.3.cjs
